language: python
python:
- '2.7'
- pypy
install:
- pip install -r requirements.txt
services:
- mongodb
script: python manage.py test
before_install:
- openssl aes-256-cbc -d -a -in client_secrets2.json.enc -out silo/client_secrets.json -k $SECRET_PASS
